### ISSUE TITLE
textarea placeholder doesn't work

### ISSUE THREAD

**Issue by joanscript** [Antonio-Laguna/jqueryTranslator#1]
Hi there

while the placeholder in the input works perfectly:
<input type="text" name="message" id="message" placeholder="Escribe un mensaje" data-translate="write-message" >

If we use the textarea instead, the translated text appears as the value of the textarea, not as the placeholder.
<textarea name="message" id="message" placeholder="Escribe un mensaje" data-translate="write-message"></textarea>

Could u please check this issue?
Thanks!

**Comment by joanscript** [comment]
Well, basically is adding this option:
translateElement : function (elem, value){
            if (elem.is('input') || elem.is('textarea')) {
                if (elem.is('[placeholder]'))
                    elem.attr('placeholder', value);
                else
                    elem.val(value);
            }
            else if (elem.is('optgroup')){
                elem.attr('label', value);
            }
            else if (elem.is('img')) {
                elem.attr('alt',value);
            }
            else {
                elem.html(value);
            }
        }

**Comment by Antonio-Laguna** [comment]
Hi @joanscript I would take a look on this and will commit to solve this.

Thank you very much for your time :+1:
