### ISSUE TITLE
I seem to have met a BUG

### ISSUE THREAD

**Issue by robincodex** [Antonio-Laguna/jqueryTranslator#11]
My browser language is zh-CN,  it successfully loaded the `/languages/common-zh-CN.json` file.
But console display the following error:

![image](https://cloud.githubusercontent.com/assets/8408783/17749002/8e38d9c4-64ee-11e6-91f5-1d61fadb8565.png)

**Comment by leandroferrete** [comment]
Try put this in your web.config file inside <staticContent>
`<mimeMap` fileExtension=".json" mimeType="application/json" />
