### ISSUE TITLE
demo-es-ES.json isn't working

### ISSUE THREAD

**Issue by stevenmunoz** [Antonio-Laguna/jqueryTranslator#3]
Hi !!! 
Im testing the plugin and it's working fine with my demo-es.json file, but now I'm trying to load a demo-es-ES.json file and it doesn't translate the page, I alert the language in the plugin and it's es-ES ... what I'm losing ? ... in page documentation says that it will search demo-es-ES.json format too. But I don't know why It doesn't work ?
I'm using jquery-1.9.0.min.js and latest github version of jqueryTranslator.js 

And I'm initializing with this function

<script>
     (function(){
          $("[data-translate]").jqTranslate('demo');
       })();
</script>

thanks.

**Comment by Antonio-Laguna** [comment]
Can I see more code or something online?

**Comment by stevenmunoz** [comment]
Sorry for late !!! ... actually I don't have more than one label and all the files downloaded with demo, I was looking for some reason and I think that plugin is only searching for demo-es or demo-ES json ... in spite of Im actually testing with demo-es.json and It's and incredible plugin, your job is amazing, and it will provide me a really good translation solution. :)

**Comment by Antonio-Laguna** [comment]
Hi Steven,

It says that _if_ the browser sends also the locale, it will **also** try to get the other file. You have to be sure that is getting the locale (as that's not the usual behaviour). If you have an example that's working and failing let me know and I try to help.

I'm clossing this now. Feel free to reopen if you have further information.

**Comment by santosh-k1** [comment]
Find the same issue ... i have created 2 json file and try to call but unable to call and translate the test.. whatever you have provided the demo its just simple text not getting the text from demo-es,json...
  
![language-translate-issue](https://user-images.githubusercontent.com/4470369/29363813-f60f31f4-82ae-11e7-81ef-e9f257076cd4.png)
